name: Continuous Delivery System
on:
  push:
    branches:
      - main

jobs:
  deliverSystem:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Teste de continious delivery
        uses: actions/upload-artifact@v4
        with:
          name: ATPdevops
          path: |
            main.py
            README.md
            LICENSE
            
  deploy:
    runs-on: ubuntu-latest
    needs: deliverSystem
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ATPdevops
      - name: Display structure of downloaded files
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3